spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Optional, for automatic schema updates
    show-sql: true # Optional, to log SQL queries